version: '3.6'
services:
  tf:
    image: "hashicorp/terraform:0.14.8"
    container_name: "tform"
    volumes:
    - .:/infra
    working_dir: /infra
    environment:
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
#    - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}